//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UDS.Study
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum cr4de_rent_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Canceled", 3, "#0000ff")]
		Canceled = 420660005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Confirmed", 2, "#0000ff")]
		Confirmed = 420660001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Created", 0, "#0000ff")]
		Created = 420660000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Renting", 1, "#0000ff")]
		Renting = 420660002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Returned", 4, "#0000ff")]
		Returned = 420660006,
	}
}