//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UDS.Study
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum cr4de_cartransferreport_cr4de_Type
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Pickup", 0, "#0000ff")]
		Pickup = 420660000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Return", 1, "#0000ff")]
		Return = 420660001,
	}
}